### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by infinite-horizon219** [collective/Collective#1906] opened 2024-10-13 14:27 UTC
Hello,

I hope this message finds you well. I am writing to formally request to be added to the collective organization. I am eager to contribute and collaborate with others who share similar goals and values.

I believe that being part of this collective will not only enhance my own knowledge and skills but also allow me to contribute positively to our shared objectives.

Thank you for considering my request. I look forward to the opportunity to be part of this vibrant community.

Best regards,

Ghulam Ahmed

**Comment by gforcada** [comment] 2024-10-13 20:53
Duplicate of https://github.com/collective/Collective/issues/1905

**Closed as not planned by gforcada** 2024-10-13 20:53 UTC
Labels: Request
